name: build-rpi5-arm64
on:
  push:
    paths:
      - "picture2notes_client.py"

jobs:
  build-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Enable QEMU binfmt
        run: docker run --privileged --rm tonistiigi/binfmt --install all

      - name: Build ARM64 onefile
        run: |
          docker run --rm --platform linux/arm64/v8 -v "$PWD":/src -w /src \
            python:3.12-bookworm bash -lc "
              pip install --upgrade pip wheel &&
              pip install pyinstaller pyyaml pyserial websockets sentry-sdk &&
              pyinstaller --onefile --console --name unified_client --hidden-import sentry_sdk picture2notes_client.py
            "

      - uses: actions/upload-artifact@v4
        with:
          name: unified-client-arm64
          path: dist/unified_client
